// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//! Build script to generate C header for Chapel

fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").expect("TODO: handle error");

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("BET_CHAPEL_H")
        .with_documentation(true)
        // Preserve the SPDX/copyright header on the generated file. cbindgen
        // overwrites include/betlang.h wholesale on every build; without this
        // the licence header is silently stripped each time (an automated
        // licence edit, which estate policy forbids — keep it manual & stable).
        .with_header(
            "// SPDX-License-Identifier: MPL-2.0\n\
             // Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>\n\
             // GENERATED by cbindgen (build.rs) — do not edit by hand.",
        )
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("include/betlang.h");

    println!("cargo:rerun-if-changed=src/lib.rs");
}
