// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vscode from "vscode";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as $$Node from "vscode-languageclient/node";

var client = {
  contents: undefined
};

function startLanguageClient(context) {
  var config = Vscode.workspace.getConfiguration("betlang");
  var path = config.get("lspPath");
  var serverPath = path !== undefined ? path : "bet-lsp";
  var serverOptions_run = {
    command: serverPath,
    transport: 0
  };
  var serverOptions_debug = {
    command: serverPath,
    transport: 0,
    options: {
      env: Js_dict.fromArray([[
              "RUST_BACKTRACE",
              "1"
            ]])
    }
  };
  var serverOptions = {
    run: serverOptions_run,
    debug: serverOptions_debug
  };
  var clientOptions_documentSelector = [{
      scheme: "file",
      language: "betlang"
    }];
  var clientOptions_synchronize = {
    fileEvents: Vscode.workspace.createFileSystemWatcher("**/*.{bet,betlang}")
  };
  var clientOptions = {
    documentSelector: clientOptions_documentSelector,
    synchronize: clientOptions_synchronize
  };
  var languageClient = new $$Node.LanguageClient("betlang", "Betlang Language Server", serverOptions, clientOptions);
  client.contents = Caml_option.some(languageClient);
  languageClient.start();
}

function restartServer(context) {
  var c = client.contents;
  if (c !== undefined) {
    Caml_option.valFromOption(c).stop();
    return startLanguageClient(context);
  } else {
    return startLanguageClient(context);
  }
}

function activate(context) {
  startLanguageClient(context);
  var restartCmd = Vscode.commands.registerCommand("betlang.restartServer", (function () {
          return new Promise((function (resolve, param) {
                        restartServer(context);
                        resolve();
                      }));
        }));
  var replStartCmd = Vscode.commands.registerCommand("betlang.startRepl", (function () {
          return new Promise((function (resolve, param) {
                        Vscode.window.showInformationMessage("REPL not yet implemented");
                        resolve();
                      }));
        }));
  var replStopCmd = Vscode.commands.registerCommand("betlang.stopRepl", (function () {
          return new Promise((function (resolve, param) {
                        Vscode.window.showInformationMessage("REPL not yet implemented");
                        resolve();
                      }));
        }));
  var evalCmd = Vscode.commands.registerCommand("betlang.evalSelection", (function () {
          return new Promise((function (resolve, param) {
                        Vscode.window.showInformationMessage("Eval not yet implemented");
                        resolve();
                      }));
        }));
  context.subscriptions.push(restartCmd);
  context.subscriptions.push(replStartCmd);
  context.subscriptions.push(replStopCmd);
  context.subscriptions.push(evalCmd);
}

function deactivate() {
  var c = client.contents;
  if (c !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(c).stop());
  }
  
}

export {
  client ,
  startLanguageClient ,
  restartServer ,
  activate ,
  deactivate ,
}
/* vscode Not a pure module */
